@echo off
echo Aguardando servidor encerrar...
timeout /t 2 /nobreak > nul
echo Reiniciando servidor...
start "Servidor EVM" "c:\nvgt\nvgtw.exe" "C:/Users/User/Documents/meus arquivos/nvgt/projetos/projetoIg/server/server.nvgt"
